### ISSUE TITLE
about test.txt

### ISSUE THREAD

**Issue by gzz1529657064** [GuodongQi/yolo3_tensorflow#1]
博主，测试集test.txt如何使用？也就是如何检测测试集图片所产生的预测框。并保存为txt文件。我在yolo.py里打印了
print(picked_boxes)
得到下面这个结果：
[array([200.927948  , 102.86123657, 210.12561035, 121.94422913,
         0.99612319,   5.        ])]
也就是xmin、ymin、xmax、ymax、score、class_idx
但是不知道怎么用一个for循环读取test.txt,并把预测框结果保存起来。
十分感谢！！！！！

**Comment by GuodongQi** [comment]
这属于文件的操作le , 可以参考以下格式

```
# 读取test.txt
with open('test.txt', 'r') as old_file:
      imgs= old_file.readlines()
new_file =open('test.txt', 'w')  

# yolo
for img_path in imgs:
      picked_boxes = yolo(img_path)

      # write img_path and box in new file
      new_file.write(img_path)  # wirite img_path
      for box in picked_boxes:   # write box
            box_string = ‘,’.join(map(str,box))   
            # 200.927948 , 102.86123657, 210.12561035, 121.94422913, 0.99612319, 5. 
            new_file.write(box_string+' ')
      new_file.write('\n')
     






```

**Comment by gzz1529657064** [comment]
嗯嗯，十分感谢！我试试。

**Comment by gzz1529657064** [comment]
博主，你的代码我不知道该放到那个文件中？如果是单独的作为一个文件运行，我也试过，但是好像不行。
这行代码：
picked_boxes = yolo(img_path)

如果能得到这样的结果就好了。
输入一个test.txt 
里面的内容是：
xxx/00001.jpg, xmin,ymin,xmax,ymax,class_idx
xxx/00002.jpg, xmin,ymin,xmax,ymax,class_idx
.....

最后输出:
00001.txt
类别 分数 xmin ymin xmax ymax

00002.txt
类别 分数 xmin ymin xmax ymax

**Comment by gzz1529657064** [comment]
博主，你的代码我不知道该放到那个文件中？如果是单独的作为一个文件运行，我也试过，但是好像不行。
这行代码：
picked_boxes = yolo(img_path)
好像不太对

如果能得到这样的结果就好了。
输入一个test.txt
里面的内容是：
xxx/00001.jpg, xmin,ymin,xmax,ymax,class_idx
xxx/00002.jpg, xmin,ymin,xmax,ymax,class_idx
.....

最后输出:
00001.txt
类别 分数 xmin ymin xmax ymax

00002.txt
类别 分数 xmin ymin xmax ymax

我觉得这些应该添加到yolo.py中吧

**Comment by GuodongQi** [comment]
是的，直接在yolo.py里追加。 picked_boxes = yolo(img_path) 这一行我是简写的。
**参考yolo.py第70行，返回所有的box（包含分数较低的），随后74行是对这些box进行筛选。**
因为预测时batch_size = 1, 所以有了73行，79行。如果你需要同时预测多个图片，可以修改73，79行。相应的input_shape 也需要改一下。
76 77 78 行是将box画出来，可以删去加快速度。
