### ISSUE TITLE
还有个问题，我训练的mobilenetv2版本的yolo3    loss在10以上正常吗？请问您这面训练的是多少呢？

### ISSUE THREAD

**Issue by Wangfeng2394** [GuodongQi/yolo3_tensorflow#10]
还有个问题，我训练的mobilenetv2版本的yolo3    loss在10以上正常吗？请问您这面训练的是多少呢？谢谢啦

**Comment by GuodongQi** [comment]
正常，loss只是一个参考值。
你可以使用tensorboard，查看模型在验证集上的各类别AP，以及mAP，这个更有说服力，具体看readme.md有个截图事例

**Comment by Wangfeng2394** [comment]
我觉得是我模型的问题，你这个里面能直接加tensorflow自带的样本增强吗 我再用cpp写样本增强的代码。比如旋转之类的。

**Comment by GuodongQi** [comment]
不能，因为我读数据是用opencv，处理数据是numpy。不是tensor数据类型，无法直接处理。这也是模型训练速度慢的主要原因，都开销在预处理了。后面会改进，两个思路，一是使用多进程处理数据(目前在搞，总是遇到一些错误)，二是使用tfrecord(可能不够灵活)。 
如果你想进行旋转的话，可以先用numpy完成，网上应该有类似的函数

**Comment by Wangfeng2394** [comment]
而且内存占用的多   
谷歌的tensorflow_model object detection api  我训练的mobilenet ssd 的batchsize可以设置到将近100.
用这个代码最多到10.

**Comment by Wangfeng2394** [comment]
tfrecord 很好啊，如果用tfrecord我觉得使用这个开源的人会更多  毕竟tfrecord是tensorflow的亲儿子啊。标准在那摆着

**Comment by GuodongQi** [comment]
@HKVINS89757 如果要用tfrecord那代码得大改了:joy:

**Comment by GuodongQi** [comment]
@HKVINS89757 占用内存大小和模型参数量有关，yolov3的参数量还是挺大的

**Comment by Wangfeng2394** [comment]
@GuodongQi   谢谢您的耐心答疑。
