### ISSUE TITLE
你好 ，我用脚本跑出来的 yolo3 mobilenet2 的输出节点为 yolo_head2/cnn/Variable

### ISSUE THREAD

**Issue by Wangfeng2394** [GuodongQi/yolo3_tensorflow#12]
但是用 这个节点作为输出节点冻结模型的时候，模型只有49kb  咋回事 ，这个不是输出节点么？？

**Comment by GuodongQi** [comment]
你好，输出节点有三个，因为是多尺度输出，fe1, box1, grid1; fe2, box2, grid2, ....
https://github.com/GuodongQi/yolo3_tensorflow/blob/35f3e78ef5443273407f79b519387c50df410334/net/yolo3_net.py#L211-L235

**Comment by Wangfeng2394** [comment]
好的 谢谢哦。 大佬你是删库跑路吗? 问题都删了

那反应的tensorflow训练出的模型节点里应该就是  ：yolo_head1/cnn/Variable_1/Assign 、yolo_head2/cnn/Variable_1/Assign、yolo_head3/cnn/Variable_1/Assign  么？

**Comment by GuodongQi** [comment]
是的。
只是close了已经解决的issue，没有删

**Comment by Wangfeng2394** [comment]
是 yolo_head1/cnn/Variable_1 ？还是yolo_head1/cnn/Variable_1/Assign   这个怎么判定呢？
