### ISSUE TITLE
你好，关于mobilenet v2的网络结构

### ISSUE THREAD

**Issue by Wangfeng2394** [GuodongQi/yolo3_tensorflow#13]
`elif net_type == 'mobilenetv2':
        # down sample
        x = conv_block(x, [3, 3], [2, 2], 32, 'cnn', is_training=is_training)

        # down sample
        x = conv_block(x, [3, 3], [2, 2], 64, net_type, is_training=is_training)
        for i in range(2):
            x = residual(x, net_type, is_training, 64, 1)

        # down sample
        x = conv_block(x, [3, 3], [2, 2], 96, net_type, is_training=is_training)
        for i in range(4):
            x = residual(x, net_type,is_training, 96, 6)
        route2 = x

        # down sample
        x = conv_block(x, [3, 3], [2, 2], 160, net_type, is_training=is_training)
        for i in range(4):
            x = residual(x, net_type, is_training, 160, 6)
        route1 = x

        # down sample
        x = conv_block(x, [3, 3], [2, 2], 320, net_type, is_training=is_training)
        for i in range(3):
            x = residual(x, net_type, is_training, 320, 1)
`

**Comment by Wangfeng2394** [comment]
感觉跟mobilenet标准的图对不上呀 从第一个for循环开始乱的

第一个for循环应该是只循环一次 然后前面加个带倒置残差的下采样吧

**Comment by Wangfeng2394** [comment]
窃以为 mobilenet v2 的模型是不是应该这样： 请大佬斧正
`   elif net_type == 'mobilenetv2':#

        print('MobileNet V2 ------------------ input image batch’s shape:',x.shape)
	#x 为   416×416 图像  标准的mobilnet v2 输入为 224 ×224有一定差异  
        x = conv_block(x, [3, 3], [2, 2], 32, 'cnn', is_training=is_training)	#conv2d正常卷积，输出208×208×32通道
        
        print('1 ------------------ input image batch’s shape:',x.shape)
        x = conv_block(x, [3, 3], [2, 2], 16, net_type, is_training=is_training) #残差块卷积，输出104×104×16 下采样
        x = conv_block(x, [3, 3], [1, 1], 24, net_type, is_training=is_training) #残差块卷积，输出104×104×24
        x = residual(x, net_type, is_training, 24, 1)#残差块卷积，输出104×104×24
        x = conv_block(x, [3, 3], [2, 2], 32, net_type, is_training=is_training) #残差块卷积，输出52×52×32   下采样
        #print('2 ------------------ input image batch’s shape:',x.shape)
        for i in range(2):# 残差块卷积 输出 52×52×32
            x = residual(x, net_type, is_training, 32, 1)
        #print('21 ------------------ input image batch’s shape:',x.shape)
        print('ROUTE2 ------------------ batch’s shape:',x.shape)	
        route2 = x

        #print('4 ------------------ input image batch’s shape:',x.shape)
        x = conv_block(x, [3, 3], [2, 2], 64, net_type, is_training=is_training)#残差块卷积，输出26×26×64   下采样
        for i in range(3):# 残差块卷积 输出 26×26×64  
            x = residual(x, net_type, is_training, 64, 6)
        x = conv_block(x, [3, 3], [1, 1], 96, net_type, is_training=is_training)#残差块卷积，输出26×26×96   更改输出通道
        for i in range(2):# 残差块卷积 输出 26×26×64  
            x = residual(x, net_type, is_training, 96, 6)
        print('ROUTE1 ------------------ batch’s shape:',x.shape)
        route1 = x

        # down sample
        print('5 ------------------ input image batch’s shape:',x.shape)
        x = conv_block(x, [3, 3], [2, 2], 160, net_type, is_training=is_training)#残差块卷积，输出13×13×160 下采样
        for i in range(2):
            x = residual(x, net_type, is_training, 160, 1)
        x = conv_block(x, [3, 3], [1, 1], 320, net_type, is_training=is_training)#残差块卷积，输出13×13×320 更改输出通道
        print('Final ------------------ batch’s shape:',x.shape)
    else:
        route1, route2 = [], []
    return x, route1, route2
`

**Comment by GuodongQi** [comment]
> 感觉跟mobilenet标准的图对不上呀 从第一个for循环开始乱的
> 
> 第一个for循环应该是只循环一次 然后前面加个带倒置残差的下采样吧

是的，通道数我这里没有按照mobilnet来写。
你可以提一个pull request，我merge到项目里

**Comment by Wangfeng2394** [comment]
> > 感觉跟mobilenet标准的图对不上呀 从第一个for循环开始乱的
> > 第一个for循环应该是只循环一次 然后前面加个带倒置残差的下采样吧
> 
> 是的，通道数我这里没有按照mobilnet来写。
> 你可以提一个pull request，我merge到项目里

提了

**Comment by Wangfeng2394** [comment]
感觉改之后可以设置的batch size翻了一倍 我1080ti的渣渣显卡可以调到16了

**Comment by GuodongQi** [comment]
nice！已merge，感谢
