### ISSUE TITLE
你好，我训练时候loss 从一千多降到一百多 ，貌似就降不动了，map很低，正常吗？

### ISSUE THREAD

**Issue by feifeiwei** [GuodongQi/yolo3_tensorflow#16]

**Comment by GuodongQi** [comment]
训练了多少个epoch？ 开始时loss下降快，后来就比较慢了，试试看60个epoch的mAP

**Comment by feifeiwei** [comment]
训了不到十个，mobilenet2的backbone， loss 现在在130左右。  还有个问题是， 你这里的anchor需要做处理吗？ 比如我训练数据原始尺寸1280x720， kmean了6个anchors。 但是输入数据我压缩了下  640x360了,  anchors大小这里 需要除2吗？

**Comment by GuodongQi** [comment]
10个epoch有点少，需要继续训练，loss在不断震荡，会缓慢下降，同时mAP也会逐渐增大。
anchor也要手动除2

**Comment by feifeiwei** [comment]
明白了，谢谢回答
