### ISSUE TITLE
train by mobilenet 

### ISSUE THREAD

**Issue by zhuyonggan** [GuodongQi/yolo3_tensorflow#17]
python  train.py  -n mobilenetv1/v2 
报错如下：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 358, in <module>
    YOLO(configs).train()
  File "train.py", line 230, in train
    raise Exception('restore body failed, please check the pretained weight')
Exception: restore body failed, please check the pretained weight
应该是预训练模型的问题？用yolov3.weights不行？或者这个该从哪获取？小白入门，求大佬指点

have fixed ：跳过预训练模型载入，从头训练就行

**Comment by GuodongQi** [comment]
是的，因为没有mobilenet预训练权重
