### ISSUE TITLE
关于训练网络类型选择和预训练模型的问题

### ISSUE THREAD

**Issue by huoguangdiandian** [GuodongQi/yolo3_tensorflow#2]
您好，首先非常感谢分享代码，我在训练模型时遇到两个问题
1、网络类型修改为mobilenetv2时提示TypeError: `pred` must be a Tensor, or a Python bool, or 1 or 0. Found instead: 64
2、网络类型选择为mobilenet时，预训练模型加载失败，预训练模型只有darknet的吗还是mobilenet模型只能从头开始训练

**Comment by GuodongQi** [comment]
你好：

1. 能否给出错误具体出现在什么位置。
2. 是的，只能从头开始训练，mobilenet收敛比较慢，可能需要较多的epoch。

**Comment by huoguangdiandian** [comment]
![1565329834(1)](https://user-images.githubusercontent.com/45250079/62757120-c7c18300-baac-11e9-9e77-895fbea236c2.jpg)

**Comment by huoguangdiandian** [comment]
这是报错信息，我刚找了一下，是在yolo3_net.py第92行这个函数里有错误

**Comment by huoguangdiandian** [comment]
好像mobilenetv2写的不全，中间有好几个残差块没写

**Comment by GuodongQi** [comment]
上次修改batchnorm时，残差块is_training参数忘了补全，现在已经修复问题，感谢反馈。[点击查看](https://github.com/GuodongQi/yolo3_tensorflow/commit/94bb2dbaf0340f332e59ef705bdf3dbaff97b8c2)

**Comment by huoguangdiandian** [comment]
请问batch_size的值最大能到多少？我取16的时候显存不够用，取8是正常的。

**Comment by GuodongQi** [comment]
根据自己实际情况设置即可，按照你的情况，设置8比较合理。如果你显卡是v100，那可以更大

**Comment by huoguangdiandian** [comment]
好的，谢谢了。。。。
