### ISSUE TITLE
请问自己的训练集的文件结构是什么样子的？

### ISSUE THREAD

**Issue by daidaiershidi** [GuodongQi/yolo3_tensorflow#23]
`if is_train:`
`    image_dir = ''  # your train image dir`
`    annotation_dir = ''  # your train image annotation  dir`
`    gen_files = 'train.txt'`

针对这3行，请问训练集结构是下面这个样子吗？

> image_dir
> > 第1类
> > > 1.jpg
> > > 2.jpg

> > 第2类
> > ...

> annotation_dir
> > 第1类
> > > 1.jpg的annotation文件（.txt）
> > > 2.jpg的annotation文件（.txt）

> > 第2类
> > ...

还有train.txt里是什么格式啊

**Comment by GuodongQi** [comment]
你好，数据集格式无要求。重点是train.txt里的内容。
具体看readme.md
```
Row format: image_file_path box1 box2 ... boxN
Box format: x_min,y_min,x_max,y_max,class_id (no space)
```
