### ISSUE TITLE
train.py [PROBLEM]

### ISSUE THREAD

**Issue by Shotaro-N** [GuodongQi/yolo3_tensorflow#4]
help me.
I get this error in train.py.
![キャプチャ](https://user-images.githubusercontent.com/53394150/64422639-84742780-d0df-11e9-9c1d-95f07f9b09c9.PNG)

**Comment by GuodongQi** [comment]
check your  `train.txt` and `valid.txt` 
```imagepath xmin ymin xmax ymax class_index```
your  'class_index' may be larger than 'len(total_classes)'

**Comment by Shotaro-N** [comment]
Thank you for your reply
I checked train.txt, valid.txt, and voc_classestxt, but found no mistakes.
Can you think of other mistakes?

**Comment by GuodongQi** [comment]
hello 
"gds" means the grids. 
"div",'mod'  : one of these 9 (or 6) grids.
"i" "j" means the index grid cell.
The error means "i" is larger than grid shape
According to the following codes
```
               ------>  x0, y0, w, h = per_label[:4]
                        if w == 0 or h == 0:
                            continue
                        box_iou = box_anchor_iou(self.anchors, per_label[2:4])
                        k = np.argmax(box_iou)
                        div, mod = divmod(int(k), 3)
                        div = len(grid_shape) - 1 - div
                        h_r = self.hw[0] / gds[div].shape[0]
                        w_r = self.hw[1] / gds[div].shape[1]
               ------>  i = int(np.floor(x0 / w_r))
                        j = int(np.floor(y0 / h_r))
``` 
Maybe your label  `imagepath xmin ymin xmax ymax class_index` 
"xmax" is larger than image width.

**Comment by Shotaro-N** [comment]
Thank you very much！！！！
That is correct

**Comment by Shotaro-N** [comment]
Let me ask one more question
How can I display accuracy on a tensorboard?

**Comment by GuodongQi** [comment]
hello, it haven't been implemented，we could calculate mAP dring validation.
I will add  in 2 days.

**Comment by GuodongQi** [comment]
Done， please check the latest code and readme.md

**Comment by Shotaro-N** [comment]
Thank you so much!!!
