### ISSUE TITLE
应该有个地方错了吧

### ISSUE THREAD

**Issue by Wangfeng2394** [GuodongQi/yolo3_tensorflow#8]

**Comment by Wangfeng2394** [comment]
在yolo3_net.py中  mobilenet v2 下面  
  if relu:
              x = tf.layers.batch_normalization(x, training=is_training)


应该改为：
   if relu:
                    x = tf.layers.batch_normalization(x, training=is_training)
                    x = tf.nn.relu6(x)


少了一个激活

**Comment by HKVINS89757** [comment]
在yolo3_net.py中  mobilenet v2 下面  
  if relu:
              x = tf.layers.batch_normalization(x, training=is_training)


应该改为：
   if relu:
                    x = tf.layers.batch_normalization(x, training=is_training)
                    x = tf.nn.relu6(x)


少了一个激活

**Comment by HKVINS89757** [comment]
在yolo3_net.py中  mobilenet v2 下面  
  if relu:
              x = tf.layers.batch_normalization(x, training=is_training)


应该改为：
   if relu:
                    x = tf.layers.batch_normalization(x, training=is_training)
                    x = tf.nn.relu6(x)


少了一个激活

**Comment by GuodongQi** [comment]
大佬看的仔细，感谢提出
