### ISSUE TITLE
有个问题，mobilenetv2是有Bottleneck结构的，您这个mobilenetv2 好像没有吧？

### ISSUE THREAD

**Issue by Wangfeng2394** [GuodongQi/yolo3_tensorflow#9]
大佬方便解惑吗

**Comment by GuodongQi** [comment]
有的, 第70行，原模型是扩张了6倍，我这里写了3倍（因为随着深度增加，网络通道数已经很高了）
https://github.com/GuodongQi/yolo3_tensorflow/blob/35f3e78ef5443273407f79b519387c50df410334/net/yolo3_net.py#L69-L86

**Comment by Wangfeng2394** [comment]
哦哦哦   谢谢大佬  这段代码里的  if relu: 

             x = tf.layers.batch_normalization(x, training=is_training)   是不是也要激活一下啊

**Comment by Wangfeng2394** [comment]
方便加个qq请教一下吗  我的是591883385

**Comment by GuodongQi** [comment]
@HKVINS89757 根据论文模型来看，这里是线性激活函数，故直接输出x就可。

不过详查后发现，depthwise操作后应有个relu6激活，漏了

**Comment by Wangfeng2394** [comment]
我都加上relu6  感觉训练的map比不加的搞个2%左右

**Comment by GuodongQi** [comment]
@HKVINS89757 论文里说之所以不用relu6是因为前面用过了并且是压缩后的，再用的话会导致丢失部分特征。可能因为我们的通道数足够大，即使使用的话也不会有影响。:smile:以实践为准

**Comment by Wangfeng2394** [comment]
好像是有这么个说法。想起来了 谢谢！
